// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: foot_print.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUnreadCountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentUserUid string `protobuf:"bytes,1,opt,name=current_user_uid,json=currentUserUid,proto3" json:"current_user_uid,omitempty"`
}

func (x *GetUnreadCountReq) Reset() {
	*x = GetUnreadCountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foot_print_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnreadCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountReq) ProtoMessage() {}

func (x *GetUnreadCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_foot_print_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountReq.ProtoReflect.Descriptor instead.
func (*GetUnreadCountReq) Descriptor() ([]byte, []int) {
	return file_foot_print_proto_rawDescGZIP(), []int{0}
}

func (x *GetUnreadCountReq) GetCurrentUserUid() string {
	if x != nil {
		return x.CurrentUserUid
	}
	return ""
}

type GetUnreadCountRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnreadCount int64 `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
}

func (x *GetUnreadCountRes) Reset() {
	*x = GetUnreadCountRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foot_print_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnreadCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRes) ProtoMessage() {}

func (x *GetUnreadCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_foot_print_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRes.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRes) Descriptor() ([]byte, []int) {
	return file_foot_print_proto_rawDescGZIP(), []int{1}
}

func (x *GetUnreadCountRes) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

var File_foot_print_proto protoreflect.FileDescriptor

var file_foot_print_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x6f, 0x6f, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x72,
	0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x10, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x55, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65,
	0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x6e,
	0x72, 0x65, 0x61, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x54, 0x0a,
	0x10, 0x46, 0x6f, 0x6f, 0x74, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x40, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65,
	0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_foot_print_proto_rawDescOnce sync.Once
	file_foot_print_proto_rawDescData = file_foot_print_proto_rawDesc
)

func file_foot_print_proto_rawDescGZIP() []byte {
	file_foot_print_proto_rawDescOnce.Do(func() {
		file_foot_print_proto_rawDescData = protoimpl.X.CompressGZIP(file_foot_print_proto_rawDescData)
	})
	return file_foot_print_proto_rawDescData
}

var file_foot_print_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_foot_print_proto_goTypes = []interface{}{
	(*GetUnreadCountReq)(nil), // 0: pb.GetUnreadCountReq
	(*GetUnreadCountRes)(nil), // 1: pb.GetUnreadCountRes
}
var file_foot_print_proto_depIdxs = []int32{
	0, // 0: pb.FootPrintService.GetUnreadCount:input_type -> pb.GetUnreadCountReq
	1, // 1: pb.FootPrintService.GetUnreadCount:output_type -> pb.GetUnreadCountRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foot_print_proto_init() }
func file_foot_print_proto_init() {
	if File_foot_print_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_foot_print_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnreadCountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foot_print_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnreadCountRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foot_print_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_foot_print_proto_goTypes,
		DependencyIndexes: file_foot_print_proto_depIdxs,
		MessageInfos:      file_foot_print_proto_msgTypes,
	}.Build()
	File_foot_print_proto = out.File
	file_foot_print_proto_rawDesc = nil
	file_foot_print_proto_goTypes = nil
	file_foot_print_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FootPrintServiceClient is the client API for FootPrintService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FootPrintServiceClient interface {
	// rpc GetFootPrints(GetFootPrintsReq) returns (GetFootPrintsRes) {}
	GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountRes, error)
}

type footPrintServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFootPrintServiceClient(cc grpc.ClientConnInterface) FootPrintServiceClient {
	return &footPrintServiceClient{cc}
}

func (c *footPrintServiceClient) GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountRes, error) {
	out := new(GetUnreadCountRes)
	err := c.cc.Invoke(ctx, "/pb.FootPrintService/GetUnreadCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FootPrintServiceServer is the server API for FootPrintService service.
type FootPrintServiceServer interface {
	// rpc GetFootPrints(GetFootPrintsReq) returns (GetFootPrintsRes) {}
	GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountRes, error)
}

// UnimplementedFootPrintServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFootPrintServiceServer struct {
}

func (*UnimplementedFootPrintServiceServer) GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadCount not implemented")
}

func RegisterFootPrintServiceServer(s *grpc.Server, srv FootPrintServiceServer) {
	s.RegisterService(&_FootPrintService_serviceDesc, srv)
}

func _FootPrintService_GetUnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FootPrintServiceServer).GetUnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FootPrintService/GetUnreadCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FootPrintServiceServer).GetUnreadCount(ctx, req.(*GetUnreadCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _FootPrintService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FootPrintService",
	HandlerType: (*FootPrintServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUnreadCount",
			Handler:    _FootPrintService_GetUnreadCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "foot_print.proto",
}
