// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: foot_print.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFootPrintsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentUserUid string `protobuf:"bytes,1,opt,name=current_user_uid,json=currentUserUid,proto3" json:"current_user_uid,omitempty"`
}

func (x *GetFootPrintsReq) Reset() {
	*x = GetFootPrintsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foot_print_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFootPrintsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFootPrintsReq) ProtoMessage() {}

func (x *GetFootPrintsReq) ProtoReflect() protoreflect.Message {
	mi := &file_foot_print_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFootPrintsReq.ProtoReflect.Descriptor instead.
func (*GetFootPrintsReq) Descriptor() ([]byte, []int) {
	return file_foot_print_proto_rawDescGZIP(), []int{0}
}

func (x *GetFootPrintsReq) GetCurrentUserUid() string {
	if x != nil {
		return x.CurrentUserUid
	}
	return ""
}

type GetFootPrintsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FootPrints []*FootPrint `protobuf:"bytes,1,rep,name=foot_prints,json=footPrints,proto3" json:"foot_prints,omitempty"`
}

func (x *GetFootPrintsRes) Reset() {
	*x = GetFootPrintsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foot_print_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFootPrintsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFootPrintsRes) ProtoMessage() {}

func (x *GetFootPrintsRes) ProtoReflect() protoreflect.Message {
	mi := &file_foot_print_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFootPrintsRes.ProtoReflect.Descriptor instead.
func (*GetFootPrintsRes) Descriptor() ([]byte, []int) {
	return file_foot_print_proto_rawDescGZIP(), []int{1}
}

func (x *GetFootPrintsRes) GetFootPrints() []*FootPrint {
	if x != nil {
		return x.FootPrints
	}
	return nil
}

type GetUnreadCountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentUserUid string `protobuf:"bytes,1,opt,name=current_user_uid,json=currentUserUid,proto3" json:"current_user_uid,omitempty"`
}

func (x *GetUnreadCountReq) Reset() {
	*x = GetUnreadCountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foot_print_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnreadCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountReq) ProtoMessage() {}

func (x *GetUnreadCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_foot_print_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountReq.ProtoReflect.Descriptor instead.
func (*GetUnreadCountReq) Descriptor() ([]byte, []int) {
	return file_foot_print_proto_rawDescGZIP(), []int{2}
}

func (x *GetUnreadCountReq) GetCurrentUserUid() string {
	if x != nil {
		return x.CurrentUserUid
	}
	return ""
}

type GetUnreadCountRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnreadCount int64 `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
}

func (x *GetUnreadCountRes) Reset() {
	*x = GetUnreadCountRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foot_print_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnreadCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRes) ProtoMessage() {}

func (x *GetUnreadCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_foot_print_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRes.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRes) Descriptor() ([]byte, []int) {
	return file_foot_print_proto_rawDescGZIP(), []int{3}
}

func (x *GetUnreadCountRes) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type FootPrint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VisitorUid string                 `protobuf:"bytes,2,opt,name=visitor_uid,json=visitorUid,proto3" json:"visitor_uid,omitempty"`
	Visitor    *User                  `protobuf:"bytes,3,opt,name=visitor,proto3" json:"visitor,omitempty"`
	UesrUid    string                 `protobuf:"bytes,4,opt,name=uesr_uid,json=uesrUid,proto3" json:"uesr_uid,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Unread     bool                   `protobuf:"varint,7,opt,name=unread,proto3" json:"unread,omitempty"`
}

func (x *FootPrint) Reset() {
	*x = FootPrint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foot_print_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FootPrint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FootPrint) ProtoMessage() {}

func (x *FootPrint) ProtoReflect() protoreflect.Message {
	mi := &file_foot_print_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FootPrint.ProtoReflect.Descriptor instead.
func (*FootPrint) Descriptor() ([]byte, []int) {
	return file_foot_print_proto_rawDescGZIP(), []int{4}
}

func (x *FootPrint) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FootPrint) GetVisitorUid() string {
	if x != nil {
		return x.VisitorUid
	}
	return ""
}

func (x *FootPrint) GetVisitor() *User {
	if x != nil {
		return x.Visitor
	}
	return nil
}

func (x *FootPrint) GetUesrUid() string {
	if x != nil {
		return x.UesrUid
	}
	return ""
}

func (x *FootPrint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FootPrint) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *FootPrint) GetUnread() bool {
	if x != nil {
		return x.Unread
	}
	return false
}

var File_foot_print_proto protoreflect.FileDescriptor

var file_foot_print_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x6f, 0x6f, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x74, 0x50, 0x72,
	0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x55, 0x69,
	0x64, 0x22, 0x42, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x74, 0x50, 0x72, 0x69, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x0b, 0x66, 0x6f, 0x6f, 0x74, 0x5f, 0x70, 0x72,
	0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x46, 0x6f, 0x6f, 0x74, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x0a, 0x66, 0x6f, 0x6f, 0x74, 0x50,
	0x72, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x3d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65,
	0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x55, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61,
	0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x6e, 0x72,
	0x65, 0x61, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x89, 0x02, 0x0a,
	0x09, 0x46, 0x6f, 0x6f, 0x74, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x69,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x55, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x07, 0x76,
	0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70,
	0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x12,
	0x19, 0x0a, 0x08, 0x75, 0x65, 0x73, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x75, 0x65, 0x73, 0x72, 0x55, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x32, 0x93, 0x01, 0x0a, 0x10, 0x46, 0x6f, 0x6f,
	0x74, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x74, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x14,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x74, 0x50, 0x72, 0x69, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f,
	0x74, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e,
	0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foot_print_proto_rawDescOnce sync.Once
	file_foot_print_proto_rawDescData = file_foot_print_proto_rawDesc
)

func file_foot_print_proto_rawDescGZIP() []byte {
	file_foot_print_proto_rawDescOnce.Do(func() {
		file_foot_print_proto_rawDescData = protoimpl.X.CompressGZIP(file_foot_print_proto_rawDescData)
	})
	return file_foot_print_proto_rawDescData
}

var file_foot_print_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_foot_print_proto_goTypes = []interface{}{
	(*GetFootPrintsReq)(nil),      // 0: pb.GetFootPrintsReq
	(*GetFootPrintsRes)(nil),      // 1: pb.GetFootPrintsRes
	(*GetUnreadCountReq)(nil),     // 2: pb.GetUnreadCountReq
	(*GetUnreadCountRes)(nil),     // 3: pb.GetUnreadCountRes
	(*FootPrint)(nil),             // 4: pb.FootPrint
	(*User)(nil),                  // 5: pb.User
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_foot_print_proto_depIdxs = []int32{
	4, // 0: pb.GetFootPrintsRes.foot_prints:type_name -> pb.FootPrint
	5, // 1: pb.FootPrint.visitor:type_name -> pb.User
	6, // 2: pb.FootPrint.created_at:type_name -> google.protobuf.Timestamp
	6, // 3: pb.FootPrint.updated_at:type_name -> google.protobuf.Timestamp
	0, // 4: pb.FootPrintService.GetFootPrints:input_type -> pb.GetFootPrintsReq
	2, // 5: pb.FootPrintService.GetUnreadCount:input_type -> pb.GetUnreadCountReq
	1, // 6: pb.FootPrintService.GetFootPrints:output_type -> pb.GetFootPrintsRes
	3, // 7: pb.FootPrintService.GetUnreadCount:output_type -> pb.GetUnreadCountRes
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_foot_print_proto_init() }
func file_foot_print_proto_init() {
	if File_foot_print_proto != nil {
		return
	}
	file_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_foot_print_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFootPrintsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foot_print_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFootPrintsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foot_print_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnreadCountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foot_print_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnreadCountRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foot_print_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FootPrint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foot_print_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_foot_print_proto_goTypes,
		DependencyIndexes: file_foot_print_proto_depIdxs,
		MessageInfos:      file_foot_print_proto_msgTypes,
	}.Build()
	File_foot_print_proto = out.File
	file_foot_print_proto_rawDesc = nil
	file_foot_print_proto_goTypes = nil
	file_foot_print_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FootPrintServiceClient is the client API for FootPrintService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FootPrintServiceClient interface {
	GetFootPrints(ctx context.Context, in *GetFootPrintsReq, opts ...grpc.CallOption) (*GetFootPrintsRes, error)
	GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountRes, error)
}

type footPrintServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFootPrintServiceClient(cc grpc.ClientConnInterface) FootPrintServiceClient {
	return &footPrintServiceClient{cc}
}

func (c *footPrintServiceClient) GetFootPrints(ctx context.Context, in *GetFootPrintsReq, opts ...grpc.CallOption) (*GetFootPrintsRes, error) {
	out := new(GetFootPrintsRes)
	err := c.cc.Invoke(ctx, "/pb.FootPrintService/GetFootPrints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *footPrintServiceClient) GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountRes, error) {
	out := new(GetUnreadCountRes)
	err := c.cc.Invoke(ctx, "/pb.FootPrintService/GetUnreadCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FootPrintServiceServer is the server API for FootPrintService service.
type FootPrintServiceServer interface {
	GetFootPrints(context.Context, *GetFootPrintsReq) (*GetFootPrintsRes, error)
	GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountRes, error)
}

// UnimplementedFootPrintServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFootPrintServiceServer struct {
}

func (*UnimplementedFootPrintServiceServer) GetFootPrints(context.Context, *GetFootPrintsReq) (*GetFootPrintsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFootPrints not implemented")
}
func (*UnimplementedFootPrintServiceServer) GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadCount not implemented")
}

func RegisterFootPrintServiceServer(s *grpc.Server, srv FootPrintServiceServer) {
	s.RegisterService(&_FootPrintService_serviceDesc, srv)
}

func _FootPrintService_GetFootPrints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFootPrintsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FootPrintServiceServer).GetFootPrints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FootPrintService/GetFootPrints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FootPrintServiceServer).GetFootPrints(ctx, req.(*GetFootPrintsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FootPrintService_GetUnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FootPrintServiceServer).GetUnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FootPrintService/GetUnreadCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FootPrintServiceServer).GetUnreadCount(ctx, req.(*GetUnreadCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _FootPrintService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FootPrintService",
	HandlerType: (*FootPrintServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFootPrints",
			Handler:    _FootPrintService_GetFootPrints_Handler,
		},
		{
			MethodName: "GetUnreadCount",
			Handler:    _FootPrintService_GetUnreadCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "foot_print.proto",
}
