version: "3"
services:
  app:
    build:
      context: ./api
      dockerfile: docker/api/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./api:/app:cached
    ports:
      - 8081:8081
    depends_on:
      - "db"
    env_file:
      - .env

  db:
    build:
      context: ./api
      dockerfile: docker/db/Dockerfile
    environment:
      MYSQL_DATABASE: finder_development
      MYSQL_ROOT_PASSWORD: finder0501
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - .api/docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 13306:3306

volumes:
  db-data:
