version: "3"
services:
  app:
    build:
      context: ./api
      dockerfile: docker/api/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./api:/app:cached
    ports:
      - 8081:8081
    depends_on:
      - "db"
    env_file:
      - .env

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: finder_development
      MYSQL_ROOT_PASSWORD: finder0501
      TZ: "Asia/Tokyo"
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 13306:3306

volumes:
  db-data:
