version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: finder_development
      MYSQL_ROOT_PASSWORD: finder0501
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 13306:3306

  grpc:
    build:
      context: ./grpc
      dockerfile: ./Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./grpc:/app:cached
    ports:
      - 50051:50051
    depends_on:
      - "db"
    env_file:
      - .env

  app:
    build:
      context: ./api
      dockerfile: ./Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./api:/app:cached
    ports:
      - 8081:8081
    depends_on:
      - "db"
      - "grpc"
    env_file:
      - .env

  # NOTE: s3のmock 必要に応じてコメントインする？
  localstack:
    image: localstack/localstack
    ports:
      - 8080:8080
      - 4566:4566
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /tmp/localstack/data
    volumes:
      - ./localstack/:/docker-entrypoint-initaws.d

volumes:
  db-data:
  localstack_data:
