version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: finder_development
      MYSQL_ROOT_PASSWORD: finder0501
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 13306:3306

  app:
    build:
      context: ./api
      dockerfile: ./Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./api:/app:cached
    ports:
      - 8081:8081
    depends_on:
      - "db"
    env_file:
      - .env

  grpc:
    build:
      context: ./grpc
      dockerfile: ./Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./grpc:/app:cached
    ports:
      - 50051:50051
    depends_on:
      - "db"
    env_file:
      - .env
volumes:
  db-data:
