version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app:cached
    ports:
      - 8080:8080
    depends_on:
      - "db"
    env_file:
      - .env

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: finder_development
      MYSQL_ROOT_PASSWORD: finder0501
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3308:3306

volumes:
  db-data: